# Generated by Django 3.2.4 on 2021-07-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('author', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/products/')),
                ('available', models.BooleanField(default=True)),
                ('typ', models.CharField(choices=[('Islamic History', 'Islamic History'), ('Islamic Cultural', 'Islamic Cultural'), ('Fiqh', 'Fiqh'), ('Tafseer', 'Tafseer'), ("A'akida", "A'akida"), ('Hadith', 'Hadith'), ('Biography', 'Biography'), ('Familial', 'Familial'), ('Invasions', 'Invasions'), ('Politics', 'Politics')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
